import type { AppConfig } from "@/types/appConfig";

export const appConfig: AppConfig = {
	apps: [
		{
			name: "设备信息X",
			description: "查看手机硬件和系统信息,该软件暂无官方网站",
			tags: ["系统工具"],
			visitUrl: "",
			icon: "https://sf0.market.xiaomi.com/thumbnail/webp/l168q80/AppStore/0ea136566b3fe4ebe2fddabad282a39435d9abfeb",
			platform: ["Android", "iOS", "macOS"],
			priceType: "freemium",
		},
		{
			name: "APKCombo Installer",
			description: "APK安装器,支持更多格式的apk安装包,例如Text.xapk",
			tags: ["系统工具"],
			sourceCode: "",
			icon: "https://avatars.githubusercontent.com/u/49289909",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "GKD",
			description: "跳广告工具(需订阅规则)",
			tags: ["系统工具"],
			visitUrl: "https://gkd.li/",
			sourceCode: "https://github.com/gkd-kit/gkd",
			icon: "https://registry.npmmirror.com/@gkd-kit/docs/0.0.1706371840771/files/.vitepress/dist/logo.svg",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "VMOS",
			description: "Android虚拟机",
			tags: ["系统工具"],
			visitUrl: "https://app.vmos.com/",
			icon: "https://img.jbzj.com/do/uploads/litimg/240307/_1A60M28.jpg",
			platform: ["Android"],
			priceType: "freemium",
		},
		{
			name: "NanoCloud",
			description: "区域节点代理式加速器(1天试用期)",
			tags: ["网络工具"],
			icon: "https://edu.360buyimg.men/assets/img/earth-CxgU7hcn.svg",
			visitUrl: "https://cloud.52iplc.com",
			sourceCode: "https://github.com/NanoCloudAir/NanoCloud",
			platform: ["Android", "Windows", "macOS"],
			priceType: "freemium",
		},
		{
			name: "Watt Toolkit",
			description: "Github加速器,原名为Steam++",
			tags: ["网络工具"],
			visitUrl: "https://steampp.net/",
			sourceCode: "https://github.com/BeyondDimension/SteamTools",
			icon: "https://store-images.s-microsoft.com/image/apps.49815.13810726275500961.53450795-b99b-437a-849b-6599bed03235.164e92bb-9c74-4d22-8a35-7e1530f9dc4e",
			platform: ["Android", "macOS", "Linux", "Windows"],
			priceType: "freemium",
		},
		{
			name: "出境易",
			description: "外囯软件下载器,内置 Google 框架",
			tags: ["网络工具"],
			sourceCode: "",
			visitUrl: "https://www.chujingapp.com/",
			icon: "https://ts4.tc.mm.bing.net/th/id/ODF.XaYdcqvEV47FmMpf504V6g",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "MeloYou",
			description: "音乐播放器,可免费播放各音乐平台的试听音乐",
			tags: ["音乐"],
			visitUrl: "http://meloyou.fun",
			sourceCode: "https://github.com/nkolp/meloyou/",
			icon: "https://image.goapk.com/goapkmarket/imgfile/20260424/241005098tle.png",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "SuperImage",
			description: "图像画质增强,纯本地运行,工作完成所需时间由你的设备性能决定",
			tags: ["图像", "本地", "AI"],
			sourceCode: "https://github.com/Lucchetto/SuperImage",
			visitUrl: "https://superimage.io/",
			icon: "https://www.openapk.net/images/icons/superimage-apk-for-android.png",
			platform: ["Android", "Windows", "macOS"],
			priceType: "freemium",
		},
		{
			name: "简记事",
			description: "写日记的,具有竖向时间轴,不适合用来做笔记",
			tags: ["办公/效率"],
			sourceCode: "https://github.com/MM2-0/Notebook",
			visitUrl: "https://notebook.m9en.com/",
			icon: "https://img.downkuai.com/logo/20250511/a1f96c32bd2dc1182097666d68a51ea7.png",
			platform: ["Android"],
			priceType: "freemium",
		},
		{
			name: "蜜蜂记账",
			description: "记账软件,纯本地运行,云端服务需自建",
			tags: ["办公/效率"],
			visitUrl: "https://count.beejz.com/",
			sourceCode: "https://github.com/TNT-Likely/BeeCount",
			icon: "https://count.beejz.com/img/logo.svg",
			platform: ["Android", "macOS", "iOS", "Web"],
			priceType: "free",
		},
		{
			name: "Kiwi Browser",
			description: "带开发人员模式的浏览器",
			tags: ["浏览器"],
			visitUrl: "https://kiwibrowsercn.github.io/",
			sourceCode: "https://github.com/kiwibrowser/src",
			icon: "https://avatars.githubusercontent.com/u/40272275",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "Gopeed",
			description: "带扩展/脚本功能的下载器",
			tags: ["下载工具"],
			visitUrl: "https://gopeed.com/",
			sourceCode: "https://github.com/GopeedLab/gopeed",
			icon: "https://ts1.tc.mm.bing.net/th/id/ODF.6YtYBdtRDTKubGiNpDxCQQ",
			platform: ["Android", "Windows", "macOS", "Linux", "iOS", "Web", "Docker", "QNAP"],
			priceType: "free",
		},
		{
			name: "Kvaseitso",
			description: "Material Design 3桌面启动器",
			tags: ["MD3", "桌面启动器"],
			visitUrl: "https://kvaesitso.mm20.de/",
			sourceCode: "https://github.com/MM2-0/Kvaesitso",
			icon: "https://kvaesitso.mm20.de/icon.png",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "自由笔记",
			description: "",
			tags: ["办公/效率"],
			visitUrl: "https://www.freenotetech.com/",
			sourceCode: "",
			icon: "https://share.freenotetech.com/statics/ic_launcher.png",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "Xmind",
			description: "思维导图",
			tags: ["办公/效率"],
			visitUrl: "https://xmind.com/download",
			sourceCode: "",
			icon: "https://ts2.tc.mm.bing.net/th/id/ODF.nmYI60Y00_N7lNZeN0iQFA",
			platform: ["Android"],
			priceType: "free"
		},
		{
			name: "WakeUp课程表",
			description: "课程管理",
			tags: ["办公/效率"],
			visitUrl: "https://www.wakeup.fun/",
			sourceCode: "",
			icon: "https://www.wakeup.fun/images/logo.png",
			platform: ["Android"],
			priceType: "free",
		},
		{
			name: "",
			description: "",
			tags: [""],
			visitUrl: "",
			sourceCode: "",
			icon: "",
			platform: ["Android"],
			priceType: "free",
		},
	],
};
