import type { SoftwareConfig } from "@/types/softwareConfig";

export const softwareConfig: SoftwareConfig = {
	enableRating: false,
	software: [
		{
			name: "设备信息X",
			description: "查看手机硬件和系统信息,该软件暂无官方网站",
			tags: ["系统工具"],
			visitUrl: "https://pp.myapp.com/detail.htm?apkName=com.ramzibachat.deviceinfo",
			icon: "https://pp.myapp.com/ma_icon/0/icon_53976156_1783404546/256",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "APKCombo Installer",
			description: "APK安装器,支持更多格式的apk安装包,例如Text.xapk",
			tags: ["系统工具"],
			sourceCode: "https://github.com/apkcombo/apkcombo-installer",
			icon: "https://avatars.githubusercontent.com/u/49289909?s=200&v=4",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "GKD",
			description: "跳广告工具(需订阅规则)",
			tags: ["系统工具"],
			sourceCode: "https://github.com/gkd-kit/gkd",
			icon: "",
			rating: 4,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "VMOS",
			description: "Android虚拟机",
			tags: ["系统工具"],
			visitUrl: "https://www.vmos.cn/",
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "Nano",
			description: "区域节点代理式加速器(1天试用期)",
			tags: ["网络工具"],
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费/付费",
		},
		{
			name: "Watt Toolkit",
			description: "Github加速器,原名为Steam++",
			tags: ["网络工具"],
			visitUrl: "https://steampp.net/",
			sourceCode: "https://github.com/BeyondDimension/SteamTools",
			icon: "",
			rating: 4,
			platform: ["Android"],
			price: "免费/付费",
		},
		{
			name: "出境易",
			description: "外囯软件下载器,内置 Google 框架",
			tags: ["网络工具"],
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "MeloYou",
			description: "音乐播放器,可免费播放各音乐平台的试听音乐",
			tags: ["music"],
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "SuperImage",
			description: "图像画质增强,纯本地运行,工作完成所需时间由你的设备性能决定",
			tags: ["Image", "Local", "AI" ],
			sourceCode: "https://github.com/bytedance/SuperImage",
			icon: "",
			rating: 4,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "简记事",
			description: "写日记的,具有竖向时间轴,不适合用来做笔记",
			tags: ["办公/效率"],
			icon: "",
			rating: 4,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "蜜蜂记账",
			description: "记账软件,纯本地运行,云端服务需自建",
			tags: ["办公/效率"],
			sourceCode: "https://github.com/zhaojunlike/Beehive",
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "KiWi Browser",
			description: "带开发人员模式的浏览器",
			tags: ["Web"],
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费/付费",
		},
		{
			name: "Gopeed",
			description: "带扩展/脚本功能的下载器",
			tags: ["下载工具"],
			visitUrl: "https://gopeed.com/",
			sourceCode: "https://github.com/GopeedLab/gopeed",
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
		{
			name: "Kvaseitso",
			description: "MD3桌面启动器",
			tags: ["MD3","桌面启动器"],
			sourceCode: "https://github.com/Kvaesitso/Kvaesitso",
			icon: "",
			rating: 5,
			platform: ["Android"],
			price: "免费",
		},
/*		{
			name: "",
			description: "",
			tags: [""],
			visitUrl: "",
			sourceCode: "",
			icon: "",
			platform: [""],
			price: "",
		},
*/	],
};